export const knownTechnologies = [
    'JavaScript',
    'TypeScript',
    'React',
    'Git',
    'Sass',
    'NPM',
    'VS Code',
    'axios',
    'HTML',
    'CSS',
    'Docker',
    // 'styled-components',
    'BEM',
    'REST API',
];
